---

# This is the ssh user you use from the control machine to the target machine
ansible_user: root

# We are using the community repo
repo: https://github.com/EOSIO/eos
version: v1.3.0

# A simple reference, it doesnt have to be a producer name
agent_name: eosbackend

# The user to create which will run nodeos, should not be root
ops_user: eos1

# Override the default install locations

# eos software like nodeos
eos_install_dir: /opt/eos
# block related files, log.txt
mainnet_install_dir: /mnt/xfs/mainnet

# Use these settings for non standard ssh port and/or ssh key
ansible_ssh_private_key_file: ~/.ssh/id_rsa.pem
# ansible_port: 4567
